# Generated by Django 2.0.4 on 2018-05-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prognostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_prognostic', models.IntegerField(default=0)),
                ('team2_prognostic', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='Match date and time')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_number', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_requests_created', to='worldcup.Team'),
        ),
        migrations.AddField(
            model_name='result',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcup.Team'),
        ),
        migrations.AddField(
            model_name='prognostic',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prognostic_requests_created', to='worldcup.Team'),
        ),
        migrations.AddField(
            model_name='prognostic',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcup.Team'),
        ),
        migrations.AddField(
            model_name='prognostic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcup.User'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcup.Team'),
        ),
    ]
